export const LOAD_NEWS = 'LOAD_NEWS';
export const SEARCH_NEWS = 'SEARCH_NEWS';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const BOOKMARK = 'BOOKMARK';
export const LOADED_BOOKMARKS = 'LOADED_BOOKMARKS'
